identifier_name:
  excluded:
    - id
large_tuple:
  warning: 5 
opt_in_rules:
  - array_init
  - attributes
#  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
#  - explicit_acl
#  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
#  - extension_access_modifier
  - fatal_error_message
#  - file_header
  - first_where
  - force_unwrapping
  - implicit_return
#  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
#  - no_extension_access_modifier
#  - no_grouping_extension
#  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
#  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
#  - strict_fileprivate
  - switch_case_on_newline
  - todo
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
disabled_rules:
  - trailing_whitespace
  - line_length
  - trailing_newline
  - explicit_top_level_acl
  - sorted_imports
  - explicit_type_interface
  - object_literal
  - conditional_returns_on_newline
  - attributes
  - let_var_whitespace
  - identifier_name
  - comment_spacing
excluded:
  - Carthage
included:
  - Mocker
  - MockerTests
